# Generated by Django 3.2.8 on 2021-10-10 17:06

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subject_images')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Test_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_file', models.FileField(upload_to='test_files')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('var1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('var2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('var3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('var4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ans', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_asnwer', models.CharField(max_length=200, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject', to='app.test')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
    ]
